#!/bin/bash

# exiftool'un kurulu olup olmadığını kontrol edin
if ! command -v exiftool &> /dev/null
then
    echo "exiftool yüklü değil. Lütfen 'brew install exiftool' ile kurun."
    exit 1
fi

# Tarih dönüştürme işlevi
convert_date() {
    local input_date="$1"
    # "UTC" kaldırma, UK/US Eylül ayı adını düzeltme ve doğru formata dönüştürme.
    echo "$input_date" | sed 's/ UTC$//' | sed 's/Sept/Sep/' | sed 's/\([0-9]\{2\}\)\.\([0-9]\{2\}\)\.\([0-9]\{4\}\), \([0-9]\{2\}\):\([0-9]\{2\}\):\([0-9]\{2\}\)/\3:\2:\1 \4:\5:\6/'
}

# Tekil JSON dosyasını işleme
process_json_file() {
    local json_file="$1"
    local dir=$(dirname "$json_file")
    local base=$(basename "$json_file" .json)
    local image_file="$dir/$base"
    
    # Görüntü dosyasının mevcut olup olmadığını kontrol
    if [ ! -f "$image_file" ]; then
        echo "Uyarı: $json_file için karşılık gelen görüntü dosyası bulunamadı."
        return
    fi
    
    echo "İşleniyor $image_file..."
    
    # JSON dosyasından veri çıkarma
    creation_time=$(jq -r '.creationTime.formatted' "$json_file" )
    photo_taken_time=$(jq -r '.photoTakenTime.formatted' "$json_file")
    latitude=$(jq -r '.geoData.latitude' "$json_file")
    longitude=$(jq -r '.geoData.longitude' "$json_file")
    altitude=$(jq -r '.geoData.altitude' "$json_file")
    
    # Tarih dizelerini doğru formata dönüştürme
    creation_time=$(convert_date "$creation_time")
    photo_taken_time=$(convert_date "$photo_taken_time")
    
    # EXIF verilerini güncelleme
    exiftool -overwrite_original \
             -CreateDate="$creation_time" \
             -DateTimeOriginal="$photo_taken_time" \
             -ModifyDate="$creation_time" \
             -FileCreateDate="$creation_time" \
             -GPSLatitude="$latitude" \
             -GPSLongitude="$longitude" \
             -GPSAltitude="$altitude" \
             "$image_file"
    
    # Dosya zaman damgasını güncelleme (Sizin JSON dosyanızda tarih formatı farklı ise ilk formatı uygun şekilde güncelleyin.)
    touch -t $(date -j -f "%e %b %Y, %H:%M:%S" "$creation_time" "+%Y%m%d%H%M.%S") "$image_file"
    
    echo "$image_file için EXIF ​​verileri ve dosya zaman damgaları güncellendi."
}

# Dizinleri yinelemeli olarak arama
process_directory() {
    local dir="$1"
    
    # Geçerli dizindeki tüm JSON dosyalarını işleme
    for json_file in "$dir"/*.json; do
        [ -e "$json_file" ] || continue  # JSON dosyalarının mevcut olup olmadığını kontrol
        process_json_file "$json_file"
    done
    
    # Alt dizinlerde yinelemeli olarak gezinme
    for subdir in "$dir"/*/ ; do
        [ -d "$subdir" ] || continue  # Alt dizin olup olmadığını kontrol
        process_directory "$subdir"
    done
}

# Geçerli dizinden işleme başla
process_directory "."

echo "Tüm alt klasörlerdeki tüm dosyalar işlendi."
